Instance: long-covid-and-ckd-bundle
InstanceOf: Bundle
Usage: #example
* type = #collection
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/observation-moca"
* entry[=].resource = observation-moca
* entry[+].fullUrl = "https://hl7.org/fhir/QuestionnaireResponse/questionnnaire-res-moca"
* entry[=].resource = questionnnaire-res-moca
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/obs-response-moca"
* entry[=].resource = obs-response-moca
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/observation-moca-original"
* entry[=].resource = observation-moca-original
* entry[+].fullUrl = "https://hl7.org/fhir/QuestionnaireResponse/questionnnaire-res-moca-original"
* entry[=].resource = questionnnaire-res-moca-original
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/obs-response-moca-original"
* entry[=].resource = obs-response-moca-original
* entry[+].fullUrl = "https://hl7.org/fhir/ServiceRequest/dialysis-request"
* entry[=].resource = dialysis-request
* entry[+].fullUrl = "https://hl7.org/fhir/Procedure/dialysis-for-bundle"
* entry[=].resource = dialysis-for-bundle
* entry[+].fullUrl = "https://hl7.org/fhir/Procedure/dialysis-for-bundle2"
* entry[=].resource = dialysis-for-bundle2
* entry[+].fullUrl = "https://hl7.org/fhir/Procedure/dialysis-for-bundle3"
* entry[=].resource = dialysis-for-bundle3
* entry[+].fullUrl = "https://hl7.org/fhir/Procedure/ckd-app-education"
* entry[=].resource = ckd-app-education
* entry[+].fullUrl = "https://hl7.org/fhir/ServiceRequest/dietitian-referral"
* entry[=].resource = dietitian-referral
* entry[+].fullUrl = "https://hl7.org/fhir/Procedure/dietitian-consult"
* entry[=].resource = dietitian-consult
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/better-diet"
* entry[=].resource = better-diet
* entry[+].fullUrl = "https://hl7.org/fhir/ServiceRequest/long-covid-request"
* entry[=].resource = long-covid-request
* entry[+].fullUrl = "https://hl7.org/fhir/MedicationRequest/med-for-chilblains"
* entry[=].resource = med-for-chilblains
* entry[+].fullUrl = "https://hl7.org/fhir/ServiceRequest/pt-3x-wk"
* entry[=].resource = pt-3x-wk
* entry[+].fullUrl = "https://hl7.org/fhir/ServiceRequest/counseling-1x-wk"
* entry[=].resource = counseling-1x-wk
* entry[+].fullUrl = "https://hl7.org/fhir/Task/meditation-7x-wk"
* entry[=].resource = meditation-7x-wk
* entry[+].fullUrl = "https://hl7.org/fhir/CarePlan/careplan-for-bundle"
* entry[=].resource = careplan-for-bundle
* entry[+].fullUrl = "https://hl7.org/fhir/RelatedPerson/daughter1"
* entry[=].resource = daughter1
* entry[+].fullUrl = "https://hl7.org/fhir/Practitioner/practitionerMCC-V"
* entry[=].resource = practitionerMCC-V
* entry[+].fullUrl = "https://hl7.org/fhir/PractitionerRole/dr-vince-jones"
* entry[=].resource = dr-vince-jones
* entry[+].fullUrl = "https://hl7.org/fhir/Practitioner/practitionerMCC-3v"
* entry[=].resource = practitionerMCC-3v
* entry[+].fullUrl = "https://hl7.org/fhir/Practitioner/careCoordinator1"
* entry[=].resource = careCoordinator1
* entry[+].fullUrl = "https://hl7.org/fhir/Organization/funding1"
* entry[=].resource = funding1
* entry[+].fullUrl = "https://hl7.org/fhir/Location/communitysite"
* entry[=].resource = communitysite
* entry[+].fullUrl = "https://hl7.org/fhir/PractitionerRole/careCoordinator-1"
* entry[=].resource = careCoordinator-1
* entry[+].fullUrl = "https://hl7.org/fhir/CareTeam/careteam-for-bundle"
* entry[=].resource = careteam-for-bundle
* entry[+].fullUrl = "https://hl7.org/fhir/Condition/patient-health-concern-1"
* entry[=].resource = patient-health-concern-1
* entry[+].fullUrl = "https://hl7.org/fhir/Condition/patient-health-concern-2"
* entry[=].resource = patient-health-concern-2
* entry[+].fullUrl = "https://hl7.org/fhir/Condition/patient-health-concern-3"
* entry[=].resource = patient-health-concern-3
* entry[+].fullUrl = "https://hl7.org/fhir/Condition/patient-health-concern-4"
* entry[=].resource = patient-health-concern-4
* entry[+].fullUrl = "https://hl7.org/fhir/Condition/careTeam-concerns-1"
* entry[=].resource = careTeam-concerns-1
* entry[+].fullUrl = "https://hl7.org/fhir/Condition/careTeam-concerns-2"
* entry[=].resource = careTeam-concerns-2
* entry[+].fullUrl = "https://hl7.org/fhir/Condition/careTeam-concerns-3"
* entry[=].resource = careTeam-concerns-3
* entry[+].fullUrl = "https://hl7.org/fhir/Condition/careTeam-concerns-4"
* entry[=].resource = careTeam-concerns-4
* entry[+].fullUrl = "https://hl7.org/fhir/Condition/careTeam-concerns-5"
* entry[=].resource = careTeam-concerns-5
* entry[+].fullUrl = "https://hl7.org/fhir/Condition/problem-list-1"
* entry[=].resource = problem-list-1
* entry[+].fullUrl = "https://hl7.org/fhir/Condition/problem-list-2"
* entry[=].resource = problem-list-2
* entry[+].fullUrl = "https://hl7.org/fhir/Condition/encounter-diag-1"
* entry[=].resource = encounter-diag-1
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/arterial-blood-gas-panel"
* entry[=].resource = arterial-blood-gas-panel
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/ph-lab-observation"
* entry[=].resource = ph-lab-observation
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/hco3-arterial-observation"
* entry[=].resource = hco3-arterial-observation
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/pCO2-arterial-observation"
* entry[=].resource = pCO2-arterial-observation
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/pO2-arterial-observation"
* entry[=].resource = pO2-arterial-observation
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/serum-lactate-observation"
* entry[=].resource = serum-lactate-observation
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/blood-ketones-observation"
* entry[=].resource = blood-ketones-observation
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/serum-electrolytes-panel"
* entry[=].resource = serum-electrolytes-panel
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/sodium-serum-observation"
* entry[=].resource = sodium-serum-observation
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/potassium-serum-observation"
* entry[=].resource = potassium-serum-observation
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/chloride-serum-observation"
* entry[=].resource = chloride-serum-observation
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/bicarbonate-serum-observation"
* entry[=].resource = bicarbonate-serum-observation
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/carbon-dioxide-serum-observation"
* entry[=].resource = carbon-dioxide-serum-observation
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/anion-gap-serum-observation"
* entry[=].resource = anion-gap-serum-observation
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/protein-serum-observation"
* entry[=].resource = protein-serum-observation
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/albumin-serum-observation"
* entry[=].resource = albumin-serum-observation
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/glomerular-filtration-observation"
* entry[=].resource = glomerular-filtration-observation
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/symptom2"
* entry[=].resource = symptom2
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/symptom3"
* entry[=].resource = symptom3
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/symptom4"
* entry[=].resource = symptom4
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/symptom5"
* entry[=].resource = symptom5
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/symptom6"
* entry[=].resource = symptom6
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/symptom7"
* entry[=].resource = symptom7
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/symptom8"
* entry[=].resource = symptom8
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/symptom9"
* entry[=].resource = symptom9
//* entry[+].fullUrl = "https://hl7.org/fhir/Condition/chilblain-found"
//* entry[=].resource = chilblain-found
* entry[+].fullUrl = "https://hl7.org/fhir/Condition/chilblain-resolved"
* entry[=].resource = chilblain-resolved
* entry[+].fullUrl = "https://hl7.org/fhir/Goal/lower-pain-minimal-opioids"
* entry[=].resource = lower-pain-minimal-opioids
* entry[+].fullUrl = "https://hl7.org/fhir/Observation/reduced-pain"
* entry[=].resource = reduced-pain
* entry[+].fullUrl = "https://hl7.org/fhir/Goal/appetite-to-normal"
* entry[=].resource = appetite-to-normal
* entry[+].fullUrl = "https://hl7.org/fhir/Goal/electrolyte-protein-normal-range"
* entry[=].resource = electrolyte-protein-normal-range
* entry[+].fullUrl = "https://hl7.org/fhir/Goal/bmi-normal-range"
* entry[=].resource = bmi-normal-range
* entry[+].fullUrl = "https://hl7.org/fhir/Goal/access-affordable-healthy-food"
* entry[=].resource = access-affordable-healthy-food